export const departamentos = {
	"Lima Metropolitana": [
		"Ancón",
		"Ate",
		"Barranco",
		"Bellavista",
		"Breña",
		"Callao",
		"Carabayllo",
		"Carmen de la Legua Reynoso",
		"Chaclacayo",
		"Cercado de Lima",
		"Chorrillos",
		"Cieneguilla",
		"Comas",
		"El Agustino",
		"Independencia",
		"Jesús María",
		"La Molina",
		"La Victoria",
		"Lince",
		"Los Olivos",
		"Lurín",
		"Magdalena del Mar",
		"Mega Plaza",
		"Miraflores",
		"Pachacámac",
		"Pucusana",
		"Pueblo Libre",
		"Puente Piedra",
		"Punta Hermosa",
		"Punta Negra",
		"Rímac",
		"San Bartolo",
		"San Borja",
		"San Isidro",
		"San Juan de Lurigancho",
		"San Juan de Miraflores",
		"San Luis",
		"San Martín de Porres",
		"San Miguel",
		"Santa Anita",
		"Santa María",
		"Santa Rosa",
		"Surco",
		"Surquillo",
		"Villa El Salvador",
		"Villa María del Triunfo",
	],
	Amazonas: ["Chachapoyas", "Bagua", "Bagua Grande"],
	Áncash: ["Huaraz", "Casma", "Chimbote", "Huarmey"],
	Apurímac: ["Abancay", "Andahuaylas"],
	Arequipa: ["Arequipa", "Camana", "Mollendo"],
	Ayacucho: ["Ayacucho", "Huanta"],
	Callao: ["Callao"],
	Cajamarca: ["Cajamarca", "Celendín", "Chota", "Jaén"],
	Cusco: ["Cusco", "Espinar", "Quillabamba", "Sicuani"],
	Huancavelica: ["Huancavelica"],
	Huánuco: ["Huánuco", "Tingo María"],
	Ica: ["Ica", "Chincha Alta", "Nazca", "Pisco"],
	Junín: ["Huancayo", "Jauja", "La Oroya", "Tarma"],
	"La Libertad": [
		"Trujillo",
		"Casa Grande",
		"Chepén",
		"Guadalupe",
		"Pacasmayo",
	],
	Lambayeque: ["Chiclayo", "Ferreñafe", "Lambayeque", "Monsefú"],
	"Lima Provincias": [
		"Barranca",
		"Cajatambo",
		"Canta",
		"Chancay",
		"Huacho",
		"Huaral",
		"Mala",
		"Matucana",
		"Oyón",
		"San Vicente de Cañete",
		"Santa Cruz de Flores",
		"Yauyos",
	],
	Loreto: ["Iquitos", "Yurimaguas", "Nauta"],
	"Madre de Dios": ["Puerto Maldonado", "Tambopata"],
	Moquegua: ["Moquegua", "Ilo"],
	Pasco: ["Cerro de Pasco"],
	Piura: [
		"Piura",
		"Catacaos",
		"Chulucanas",
		"Paita",
		"Sechura",
		"Sullana",
		"Talara",
	],
	Puno: ["Puno", "Azángaro", "Juliaca"],
	"San Martín": ["Moyobamba", "Juanjui", "Rioja", "Tarapoto"],
	Tacna: ["Tacna"],
	Tumbes: ["Tumbes", "Zarumilla"],
	Ucayali: ["Coronel Portillo", "Pucallpa", "Yurimaguas"],
};
